### ISSUE TITLE
Rosetta 2のインストール方法

### ISSUE THREAD

**Issue by minazuki0211** [flutteruniv/docs#3]
## Rosetta 2のインストール方法
flutterをインストールしてpathを通す際に、私のパソコン(MacBook Air M1,2020)ではRosetta 2をインストールしなければいけないみたいなのですが、手動でインストールしようとしても
> sudo softwareupdate --install-rosetta --agree-to-license
Password:
Installing Rosetta 2 on this system is not supported.

となってしまい、前に進むことができません。
かなり調べたのですが解決できず、八方塞がりの状態なのでご教授お願いします。
初めての質問で、書き方が間違えていたらすみません...

**Comment by kboy-silvergym** [comment]
@minazuki0211 
今気づきましたが、質問は https://github.com/flutteruniv/questions にお願いしているのでこちらはcloseします！
